name: Make Bitcoin Figures

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  make-figure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install -r requirements.txt
    - run: python make_figure.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git config pull.rebase true
        git add -A
        git commit -a --allow-empty-message -m '' || exit 0
        git pull && git push
